substitutions:
  name: espmultitest
esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: esphome.espmultitest-template
    version: "1.0"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

dashboard_import:
  package_import_url: github://esphome/esphome-project-template/project-template-esp32.yaml@v6
  import_full_config: false
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "fbc10314f075853c135d17ce545c3d25"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Espmultitest Fallback Hotspot"
    password: "V8iURHhgDln4"

captive_portal:


sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: '5C:85:7E:B0:09:31'
    temperature:
      name: "MiFlora Temperature"
    moisture:
      name: "MiFlora Moisture"
    illuminance:
      name: "MiFlora Illuminance"
    conductivity:
      name: "MiFlora Soil Conductivity"
    battery_level:
      name: "MiFlora Battery Level"
  - platform: xiaomi_hhccjcy01
    mac_address: '5C:85:7E:B0:07:35'
    temperature:
      name: "MiFlora Temperature 2"
    moisture:
      name: "MiFlora Moisture 2"
    illuminance:
      name: "MiFlora Illuminance 2"
    conductivity:
      name: "MiFlora Soil Conductivity 2"
    battery_level:
      name: "MiFlora Battery Level 2"
